
# print("你好！")
# a=input('请输入：')
# b=input('请输入：')
# print('a的内容',int(a)+int(b))
# print(type('哈哈'))
# print(type(78))
# print(type(3.55))
# print(type(True))
# print(type(()))
# print(type([]))
# print(type({}))
a=input('输入a:')
b=input('输入b:')
print('len(a)=',len(a),'len(b)=',len(b),'和=',len(a)+len(b))